services:

  # NOTE: Nginx container
  proxy:
    container_name: proxy
    image: nginx:latest
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs/:/etc/nginx/ssl:ro
    restart: always
    depends_on:
      - backend-user
      - frontend
    networks:
      - transcendence
    ports:
      - "80:80"
      - "443:443"

  # NOTE: User API container
  backend-user:
    container_name: backend-user
    build:
      context: backend-user/
      dockerfile: Dockerfile
    volumes:
      - ./backend-user:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - AVATAR_FOLDER=${AVATAR_FOLDER}
    restart: always
    networks:
      - transcendence

  # NOTE: Auth API container
  backend-auth:
    container_name: backend-auth
    build:
      context: backend-auth/
      dockerfile: Dockerfile
    volumes:
      - ./backend-auth:/app
      - /app/node_modules
    restart: always
    networks:
      - transcendence

  # NOTE: Frontend container
  frontend:
    container_name: frontend
    build:
      context: frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: always
    depends_on:
      - backend-user
    networks:
      - transcendence
    ports:
      - "5173:5173"

# volumes:

networks:
  transcendence:
    driver: bridge