services:

  proxy:
    container_name: proxy
    image: nginx:latest
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs/:/etc/nginx/ssl:ro
    restart: always
    depends_on:
      - backend
      - frontend
    networks:
      - transcendence
    ports:
      - "443:443"

  backend:
    container_name: backend
    build:
      context: backend/
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: always
    networks:
      - transcendence
    ports:
      - "3000:3000"

  frontend:
    container_name: frontend
    build:
      context: frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: always
    depends_on:
      - backend
    networks:
      - transcendence
    ports:
      - "5173:5173"

# volumes:

networks:
  transcendence:
    driver: bridge