services:

  backend:
    container_name: backend
    build:
      context: backend/
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: always
    networks:
      - transcendence
    ports:
      - "3000:3000"
    command: npm run dev

  # nginx:
  #   container_name: Nginx
  #   build:
  #     context: nginx/
  #     dockerfile: Dockerfile
  #   restart: always
  #   depends_on:
  #     - node
  #     - react
  #   networks:
  #     - transcendence

  # react:
  #   container_name: React
  #   build:
  #     context: frontend/
  #     dockerfile: Dockerfile
  #   restart: always
  #   depends_on:
  #     - node
  #   networks:
  #     - transcendence



# volumes:

networks:
  transcendence:
    driver: bridge